# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brain', '0031_auto_20171102_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField(default=django.utils.timezone.now)),
                ('cba_percentage', models.IntegerField()),
                ('performance_task', models.IntegerField()),
                ('addition_facts', models.IntegerField(blank=True, null=True)),
                ('subtraction_facts', models.IntegerField(blank=True, null=True)),
                ('multiplication_facts', models.IntegerField(blank=True, null=True)),
                ('division_facts', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoreKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField(default=django.utils.timezone.now)),
                ('assessment_name', models.CharField(max_length=255)),
                ('da1', models.IntegerField(blank=True, null=True)),
                ('da2', models.IntegerField(blank=True, null=True)),
                ('da3', models.IntegerField(blank=True, null=True)),
                ('da4', models.IntegerField(blank=True, null=True)),
                ('da5', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DRA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField(default=django.utils.timezone.now)),
                ('level_letter', models.CharField(max_length=10)),
                ('level_number', models.IntegerField()),
                ('myon_lexile', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ELAPBA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField(default=django.utils.timezone.now)),
                ('assessment_name', models.CharField(max_length=255)),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ENI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField(default=django.utils.timezone.now)),
                ('counting', models.IntegerField()),
                ('place_value', models.IntegerField()),
                ('add_sub', models.IntegerField()),
                ('mult_div', models.IntegerField()),
                ('total', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Investigations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField(default=django.utils.timezone.now)),
                ('assessment_name', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NWEA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField(default=django.utils.timezone.now)),
                ('math_rit', models.IntegerField()),
                ('math_percentile', models.IntegerField()),
                ('reading_rit', models.IntegerField()),
                ('reading_percentile', models.IntegerField()),
                ('reading_lexile', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField(default=django.utils.timezone.now)),
                ('teacher_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('blind_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('type', models.CharField(choices=[('Informational', 'Informational'), ('Narrative', 'Narrative'), ('Persuasive', 'Persuasive')], max_length=55)),
                ('pre_or_post', models.CharField(choices=[('Pre', 'Pre'), ('Post', 'Post')], max_length=55)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
