# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CGI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgi_number', models.IntegerField(unique=True, verbose_name='CGI #')),
                ('name', models.CharField(help_text='Name of the first person mentioned in the problem.', max_length=50, unique=True, verbose_name='Character Name')),
                ('question', models.TextField(help_text='Substitute __ for the numbers in the problem.', max_length=500, unique=True, verbose_name='Problem')),
                ('first_num_original', models.IntegerField(null=True, verbose_name="Original Problem's First Number")),
                ('second_num_original', models.IntegerField(null=True, verbose_name="Original Problem's Second Number")),
                ('first_num_low', models.IntegerField(verbose_name='Minimum for First Number')),
                ('first_num_high', models.IntegerField(verbose_name='Maximum for First Number')),
                ('second_num_low', models.IntegerField(verbose_name='Minimum for Second Number')),
                ('second_num_high', models.IntegerField(verbose_name='Maximum for Second Number')),
                ('gr2_unit', models.IntegerField(blank=True, help_text='The Unit in the Grade 2 Scope and Sequence which the CGI is introduced', null=True, verbose_name='Grade 2 Unit')),
                ('date_assigned', models.DateField(blank=True, help_text='Date the CGI was/will be given to the class.', null=True, verbose_name='Date Assigned')),
            ],
            options={
                'verbose_name': 'CGI Question',
                'verbose_name_plural': 'CGI Questions',
                'ordering': ['cgi_number'],
            },
        ),
        migrations.CreateModel(
            name='CGIResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(choices=[('-', '-'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', 'M')], default='-', help_text='- : Not Yet Tested, 0 : Zero Streak, 1 : One Streak, 2 : Two Streak, M : Mastered', max_length=100, verbose_name='Progress')),
                ('cgi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathcgi.CGI')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'verbose_name': 'CGI Result',
                'verbose_name_plural': 'CGI Results',
                'ordering': ['cgi'],
            },
        ),
    ]
