# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0003_auto_20170820_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='school',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
