# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0006_auto_20170820_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_exercises', models.IntegerField(default=1, help_text='Skills based off the curriculum where students must reach a score of 100.', max_length=1, verbose_name='Mastery Exercises')),
                ('cba_exercises', models.IntegerField(default=2, help_text='Skills based on the upcoming CBA.', max_length=1, verbose_name='CBA Exercises')),
                ('nwea_exercises', models.IntegerField(default=2, help_text="Skills chosen in response to a student's NWEA Scores", max_length=1, verbose_name='NWEA Exercises')),
                ('bonus_exercises', models.IntegerField(default=5, help_text='More NWEA skills, for if/when students finish the rest of their challenges.', max_length=1, verbose_name='Bonus Exercises')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.Teacher')),
            ],
        ),
    ]
