# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0007_teachersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersettings',
            name='bonus_exercises',
            field=models.IntegerField(default=5, help_text='More NWEA skills, for if/when students finish the rest of their challenges.', verbose_name='Bonus Exercises'),
        ),
        migrations.AlterField(
            model_name='teachersettings',
            name='cba_exercises',
            field=models.IntegerField(default=2, help_text='Skills based on the upcoming CBA.', verbose_name='CBA Exercises'),
        ),
        migrations.AlterField(
            model_name='teachersettings',
            name='mastery_exercises',
            field=models.IntegerField(default=1, help_text='Skills based off the curriculum where students must reach a score of 100.', verbose_name='Mastery Exercises'),
        ),
        migrations.AlterField(
            model_name='teachersettings',
            name='nwea_exercises',
            field=models.IntegerField(default=2, help_text="Skills chosen in response to a student's NWEA Scores", verbose_name='NWEA Exercises'),
        ),
    ]
