# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 13:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0008_auto_20170826_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachersettings',
            options={'verbose_name': 'Teacher Setting', 'verbose_name_plural': 'Teacher Settings'},
        ),
        migrations.AlterField(
            model_name='dataupdate',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 17, 9, 10, 16, 296864, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='homeworkcompletion',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'Complete'), ('INCOMPLETE', 'Incomplete'), ('NOTRECEIVED', 'Not Received'), ('LATE', 'Late')], default='NOT RECEIVED', max_length=50, verbose_name='Status'),
        ),
    ]
