# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 00:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0009_auto_20170917_1310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Classroom',
        ),
        migrations.AlterModelOptions(
            name='behaviorreport',
            options={'ordering': ['-school_day'], 'verbose_name': 'Behavior Report', 'verbose_name_plural': 'Behavior Reports'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['last_name'], 'verbose_name': 'Classroom', 'verbose_name_plural': 'Classrooms'},
        ),
        migrations.AlterModelOptions(
            name='currentclass',
            options={'ordering': ['year', 'grade', 'classroom'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.RenameField(
            model_name='currentclass',
            old_name='teacher',
            new_name='classroom',
        ),
        migrations.RenameField(
            model_name='morningmessage',
            old_name='teacher',
            new_name='classroom',
        ),
        migrations.RenameField(
            model_name='morningmessagesettings',
            old_name='teacher',
            new_name='classroom',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='teacher',
            new_name='classroom',
        ),
        migrations.RenameField(
            model_name='teachersettings',
            old_name='teacher',
            new_name='classroom',
        ),
        migrations.AlterField(
            model_name='dataupdate',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 28, 20, 58, 22, 909721, tzinfo=utc)),
        ),
    ]
