# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 22:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0011_auto_20170929_0110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroomassignment',
            options={'ordering': ['classroom'], 'verbose_name': 'Classroom Assignment', 'verbose_name_plural': 'Classroom Assignments'},
        ),
        migrations.AlterModelOptions(
            name='currentclass',
            options={'ordering': ['grade', 'classroom'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade',
            field=models.CharField(choices=[('K', 'Kindergarten'), ('1st', '1st Grade'), ('2nd', '2nd Grade'), ('3rd', '3rd Grade'), ('4th', '4th Grade'), ('5th', '5th Grade'), ('6th', '6th Grade'), ('7th', '7th Grade'), ('8th', '8th Grade')], default='2nd', max_length=50),
        ),
        migrations.AlterField(
            model_name='dataupdate',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 30, 18, 28, 5, 479619, tzinfo=utc)),
        ),
    ]
