# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 23:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0012_auto_20170930_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentclass',
            name='year',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='workphone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='dataupdate',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 30, 19, 7, 33, 555703, tzinfo=utc)),
        ),
    ]
