# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 13:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0013_auto_20170930_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentroster',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brain.Classroom'),
        ),
        migrations.AlterField(
            model_name='dataupdate',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 1, 9, 39, 6, 942913, tzinfo=utc)),
        ),
    ]
