# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 00:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0014_auto_20171001_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataupdate',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 20, 24, 32, 475180, tzinfo=utc)),
        ),
    ]
