# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 01:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0015_auto_20171003_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomAccountPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('site', models.CharField(choices=[('IXL', 'IXL'), ('MYON', 'MYON'), ('RAZKIDS', 'RAZKIDS'), ('REMIND', 'REMIND')], max_length=100)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.Classroom')),
            ],
        ),
        migrations.AlterField(
            model_name='dataupdate',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 21, 57, 34, 629688, tzinfo=utc)),
        ),
    ]
