# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 10:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0016_auto_20171005_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingstats',
            name='current_dra',
        ),
        migrations.RemoveField(
            model_name='readingstats',
            name='goal_dra',
        ),
        migrations.RemoveField(
            model_name='readingstats',
            name='starting_dra',
        ),
        migrations.AlterField(
            model_name='classroomaccountpassword',
            name='username',
            field=models.CharField(help_text='If IXL make sure you add @btwa to the end of it.', max_length=100),
        ),
        migrations.AlterField(
            model_name='dataupdate',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 5, 6, 16, 59, 130530, tzinfo=utc)),
        ),
    ]
