# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 10:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0019_auto_20171008_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataupdate',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 9, 6, 49, 23, 137814, tzinfo=utc)),
        ),
    ]
