# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 00:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0021_auto_20171009_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingTimeSpent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_spent', models.DateField(default=datetime.date.today, verbose_name='Date Read')),
                ('time_spent', models.IntegerField(default=0, verbose_name='Time Spent Reading')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'verbose_name': 'Daily Reading Time',
                'verbose_name_plural': 'Daily Reading Times',
            },
        ),
        migrations.AlterField(
            model_name='dataupdate',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 9, 20, 38, 31, 931399, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='readingtimespent',
            unique_together=set([('student', 'date_spent')]),
        ),
    ]
