# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 20:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0022_auto_20171010_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='myon_user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dataupdate',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 11, 16, 43, 24, 69567, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='readingtimespent',
            name='time_spent',
            field=models.IntegerField(default=0, verbose_name='Minutes Spent Reading'),
        ),
    ]
