# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 20:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0024_auto_20171015_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataupdate',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 15, 16, 11, 30, 160420, tzinfo=utc)),
        ),
    ]
