# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 01:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0026_auto_20171019_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingstats',
            name='myon_quiz_average',
            field=models.FloatField(blank=True, default=0, max_length=100, verbose_name='myON Quiz Score Average'),
        ),
        migrations.AddField(
            model_name='readingstats',
            name='myon_quizzes_taken',
            field=models.IntegerField(default=0, verbose_name='myON Books Opened'),
        ),
        migrations.AlterField(
            model_name='dataupdate',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 19, 21, 34, 58, 797268, tzinfo=utc)),
        ),
    ]
