# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 20:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0027_auto_20171020_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersettings',
            name='ixl_level_display',
            field=models.CharField(choices=[('LETTERS', 'Letters'), ('GRADES', 'Grades')], default='GRADES', help_text='What is your IXL Setting? Grades (2nd Grade) or Letters (Level D)', max_length=100),
        ),
        migrations.AlterField(
            model_name='dataupdate',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 29, 16, 18, 39, 498073, tzinfo=utc)),
        ),
    ]
