# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 01:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0029_auto_20171029_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataupdate',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 21, 3, 27, 416202, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachersettings',
            name='ixl_level_display',
            field=models.CharField(choices=[('LETTERS', 'Letters'), ('GRADES', 'Grades')], default='GRADES', help_text='What is your IXL Setting? Grades (2nd Grade) or Letters (Level D)', max_length=100, verbose_name='IXL Level Display'),
        ),
    ]
