# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0031_auto_20171102_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='quickschools_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dataupdate',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 17, 47, 59, 578528, tzinfo=utc)),
        ),
    ]
