# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 22:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0032_auto_20171106_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentroster',
            name='quickschools_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dataupdate',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 18, 18, 1, 400130, tzinfo=utc)),
        ),
    ]
