# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 02:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0033_auto_20171106_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_marked', models.DateField(default=datetime.date.today, verbose_name='Date Marked')),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('T', 'Tardy'), ('EA', 'Excused Absence'), ('ET', 'Excused Tardy')], max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
        ),
        migrations.AlterField(
            model_name='dataupdate',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 22, 13, 21, 127247, tzinfo=utc)),
        ),
    ]
