# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 02:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0034_auto_20171107_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
        ),
        migrations.AlterField(
            model_name='dataupdate',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 22, 17, 58, 331267, tzinfo=utc)),
        ),
    ]
