# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 03:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0035_auto_20171107_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancealert',
            name='alert_lock',
            field=models.BooleanField(default=False, help_text='Prevents lock from being removed. Applies to previous chronically absent students'),
        ),
        migrations.AlterField(
            model_name='dataupdate',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 23, 6, 6, 189995, tzinfo=utc)),
        ),
    ]
