# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 17:02
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Challenge', max_length=250, unique=True, verbose_name='Challenge Title')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date Created')),
            ],
            options={
                'verbose_name': 'IXL Challenge',
                'verbose_name_plural': 'IXL Challenges',
                'ordering': ['-date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(default=datetime.date.today, verbose_name='Date Assigned')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ixl.Challenge')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'verbose_name': 'IXL Challenge Assignment',
                'verbose_name_plural': 'IXL Challenge Assignments',
                'ordering': ['-date_assigned', 'challenge', 'student_id'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.CharField(max_length=10)),
                ('required_score', models.IntegerField(default=80)),
                ('bonus', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ixl.Challenge')),
            ],
        ),
        migrations.CreateModel(
            name='IXLSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\w+\\-\\w+\\.\\d+$', 'Pattern must match IXL format: D-A.12')], verbose_name='Skill ID')),
                ('skill_description', models.CharField(blank=True, max_length=200, verbose_name='Skill Description')),
                ('ixl_url', models.CharField(blank=True, default='', max_length=300, verbose_name='IXL URL')),
                ('category', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'IXL Skill',
                'verbose_name_plural': 'IXL Skills',
                'ordering': ['skill_id'],
            },
        ),
        migrations.CreateModel(
            name='IXLSkillScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(default=datetime.date.today, verbose_name='Date Recorded')),
                ('score', models.IntegerField()),
                ('ixl_skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ixl.IXLSkill', verbose_name='IXL Skill ID')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'verbose_name': 'IXL Score',
                'verbose_name_plural': 'IXL Scores',
                'ordering': ['student_id', 'ixl_skill_id'],
            },
        ),
        migrations.CreateModel(
            name='IXLStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_practiced', models.IntegerField(blank=True, verbose_name='Last Practiced')),
                ('questions_answered', models.IntegerField(blank=True, verbose_name='Questions Answered')),
                ('time_spent', models.IntegerField(blank=True, verbose_name='Time Spent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'verbose_name': 'IXL Stat',
                'verbose_name_plural': 'IXL Stats',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ixlskillscores',
            unique_together=set([('student_id', 'ixl_skill_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='challengeexercise',
            unique_together=set([('challenge', 'exercise_id')]),
        ),
    ]
