# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 00:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brain', '0015_auto_20171003_0024'),
        ('ixl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IXLList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('exercises', models.TextField()),
                ('category', models.CharField(choices=[('Unit', 'Unit'), ('Remediation', 'Remediation'), ('Enrichment', 'Enrichment'), ('Other', 'Other')], max_length=65)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IXLListAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.BooleanField(default=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('number_to_assign', models.IntegerField()),
                ('ixl_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ixl.IXLList')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
        ),
    ]
