# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0018_auto_20171008_2036'),
        ('ixl', '0002_ixllist_ixllistassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IXLTimeSpent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_spent', models.DateField(default=datetime.date.today, verbose_name='Date Practiced')),
                ('aTime', models.IntegerField(default=0, verbose_name='Pre-K Time Spent')),
                ('bTime', models.IntegerField(default=0, verbose_name='Kinder. Time Spent')),
                ('cTime', models.IntegerField(default=0, verbose_name='1st Grade Time Spent')),
                ('dTime', models.IntegerField(default=0, verbose_name='2nd Grade Time Spent')),
                ('eTime', models.IntegerField(default=0, verbose_name='3rd Grade Time Spent')),
                ('fTime', models.IntegerField(default=0, verbose_name='4th Grade Time Spent')),
                ('gTime', models.IntegerField(default=0, verbose_name='5th Grade Time Spent')),
                ('hTime', models.IntegerField(default=0, verbose_name='6th Grade Time Spent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
        ),
    ]
