# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0019_auto_20171008_2120'),
        ('ixl', '0003_ixltimespent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ixltimespent',
            options={'verbose_name': 'IXL Time Spent', 'verbose_name_plural': 'IXL Time Spent'},
        ),
        migrations.AlterField(
            model_name='ixltimespent',
            name='aTime',
            field=models.IntegerField(default=0, verbose_name='Pre-K Seconds Spent'),
        ),
        migrations.AlterField(
            model_name='ixltimespent',
            name='bTime',
            field=models.IntegerField(default=0, verbose_name='Kinder. Seconds Spent'),
        ),
        migrations.AlterField(
            model_name='ixltimespent',
            name='cTime',
            field=models.IntegerField(default=0, verbose_name='1st Grade Seconds Spent'),
        ),
        migrations.AlterField(
            model_name='ixltimespent',
            name='dTime',
            field=models.IntegerField(default=0, verbose_name='2nd Grade Seconds Spent'),
        ),
        migrations.AlterField(
            model_name='ixltimespent',
            name='eTime',
            field=models.IntegerField(default=0, verbose_name='3rd Grade Seconds Spent'),
        ),
        migrations.AlterField(
            model_name='ixltimespent',
            name='fTime',
            field=models.IntegerField(default=0, verbose_name='4th Grade Seconds Spent'),
        ),
        migrations.AlterField(
            model_name='ixltimespent',
            name='gTime',
            field=models.IntegerField(default=0, verbose_name='5th Grade Seconds Spent'),
        ),
        migrations.AlterField(
            model_name='ixltimespent',
            name='hTime',
            field=models.IntegerField(default=0, verbose_name='6th Grade Seconds Spent'),
        ),
        migrations.AlterUniqueTogether(
            name='ixltimespent',
            unique_together=set([('student', 'date_spent')]),
        ),
    ]
