# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ixl', '0004_auto_20171008_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='ixlstats',
            name='ixl_user_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='IXL UserID#'),
        ),
    ]
