# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 01:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0038_auto_20171113_0155'),
        ('ixl', '0006_auto_20171009_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='IXLListChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date Created')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'verbose_name': 'IXL List Challenge',
                'verbose_name_plural': 'IXL List Challenges',
            },
        ),
        migrations.CreateModel(
            name='IXLListChallengeExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.CharField(max_length=10)),
                ('required_score', models.IntegerField(default=80)),
                ('bonus', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ixl.IXLListChallenge')),
            ],
        ),
        migrations.CreateModel(
            name='IXLListExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.CharField(max_length=10)),
                ('required_score', models.IntegerField(default=80)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='ixllist',
            name='exercises',
        ),
        migrations.AddField(
            model_name='ixllistexercise',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ixl.IXLList'),
        ),
        migrations.AlterUniqueTogether(
            name='ixllistexercise',
            unique_together=set([('list', 'exercise_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='ixllistchallengeexercise',
            unique_together=set([('challenge', 'exercise_id')]),
        ),
    ]
