# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 02:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ixl', '0007_auto_20171113_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ixllist',
            options={'verbose_name': 'IXL List', 'verbose_name_plural': 'IXL Lists'},
        ),
        migrations.AlterModelOptions(
            name='ixllistassignment',
            options={'verbose_name': 'IXL List Assignment', 'verbose_name_plural': 'IXL List Assignments'},
        ),
        migrations.AlterModelOptions(
            name='ixllistchallengeexercise',
            options={'verbose_name': 'IXL List Challenge Exercise', 'verbose_name_plural': 'IXL List Challenge Exercises'},
        ),
        migrations.AlterModelOptions(
            name='ixllistexercise',
            options={'verbose_name': 'IXL List Exercise', 'verbose_name_plural': 'IXL List Exercises'},
        ),
        migrations.AlterUniqueTogether(
            name='ixllist',
            unique_together=set([('title', 'author')]),
        ),
    ]
