# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 17:57
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('brain', '0040_auto_20171123_1757'),
        ('ixl', '0008_auto_20171119_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='IXLListSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=6)),
                ('id_code', models.CharField(max_length=6, validators=[
                    django.core.validators.RegexValidator('^\\w+\\.\\d+$', 'Pattern must match IXL format: A.12')],
                                             verbose_name='Skill ID')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Skill Description')),
                ('category', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'IXL List Skills',
                'verbose_name': 'IXL List Skill',
                'ordering': ['id_code'],
            },
        ),
        migrations.CreateModel(
            name='IXLListSkillScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(default=datetime.date.today, verbose_name='Date Recorded')),
                ('score', models.IntegerField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ixl.IXLListSkill',
                                            verbose_name='IXL List Skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'verbose_name_plural': 'IXL Scores',
                'verbose_name': 'IXL Score',
                'ordering': ['student_id', 'skill'],
            },
        ),
        migrations.AlterField(
            model_name='ixllist',
            name='category',
            field=models.CharField(
                choices=[('Unit', 'Unit'), ('Remediation', 'Remediation'), ('Enrichment', 'Enrichment'),
                         ('Test', 'Test'), ('Other', 'Other')], max_length=65),
        ),
        migrations.AlterUniqueTogether(
            name='ixllistskillscores',
            unique_together=set([('student', 'skill')]),
        ),
    ]
