# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('ixl', '0009_auto_20171123_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ixllistchallengeexercise',
            old_name='challenge',
            new_name='list_challenge',
        ),
        migrations.AddField(
            model_name='ixllistchallengeexercise',
            name='list_exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ixl.IXLListExercise'),
        ),
        migrations.AddField(
            model_name='ixllistexercise',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ixl.IXLListSkill'),
        ),
        migrations.RemoveField(
            model_name='ixllistchallengeexercise',
            name='exercise_id',
        ),
        migrations.RemoveField(
            model_name='ixllistchallengeexercise',
            name='required_score',
        ),
        migrations.AlterUniqueTogether(
            name='ixllistchallengeexercise',
            unique_together=set([('list_challenge', 'list_exercise')]),
        ),
        migrations.RemoveField(
            model_name='ixllistexercise',
            name='exercise_id',
        ),
        migrations.AlterUniqueTogether(
            name='ixllistexercise',
            unique_together=set([('list', 'skill', 'required_score')]),
        ),
    ]
