# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('hand', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Raised Hand')),
                ('slant', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='SLANT')),
                ('transition', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Transitions')),
                ('please', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Please/Thank You')),
                ('instruction', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Instructions 1st Time')),
                ('material', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Respected Materials')),
                ('peer', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Respected Peers')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('approved', models.CharField(default='NO', max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'verbose_name': 'Teacher Approval',
                'verbose_name_plural': 'Teacher Approvals',
            },
        ),
    ]
