# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 17:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCStartingTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_test', models.IntegerField(verbose_name='Starting Test')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'verbose_name': 'AMC Starting Test',
                'verbose_name_plural': 'AMC Starting Tests',
            },
        ),
        migrations.CreateModel(
            name='AMCTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.IntegerField(unique=True)),
                ('topic', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('grade_equivalent', models.CharField(max_length=100)),
                ('total_questions', models.IntegerField(default=20)),
                ('minimum_passing_grade', models.IntegerField(default=18)),
            ],
            options={
                'verbose_name': 'AMC Test',
                'verbose_name_plural': 'AMC Tests',
            },
        ),
        migrations.CreateModel(
            name='AMCTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('date_tested', models.DateField(default=datetime.date.today, verbose_name='Date Tested')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amc.AMCTest')),
            ],
            options={
                'verbose_name': 'AMC Test Score',
                'verbose_name_plural': 'AMC Test Scores',
                'ordering': ['-date_tested', 'student'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='amctestresult',
            unique_together=set([('student', 'test', 'date_tested')]),
        ),
    ]
