# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_selected', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('image', models.FilePathField(path='static/images/stickers')),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(default='CGI', max_length=255)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StickerAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned', models.BooleanField(default=True)),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badges.Sticker')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'verbose_name': 'Earned Sticker',
                'verbose_name_plural': 'Earned Stickers Assignments',
            },
        ),
        migrations.AddField(
            model_name='avatar',
            name='sticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badges.Sticker'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster'),
        ),
        migrations.AlterUniqueTogether(
            name='stickerassignment',
            unique_together=set([('student', 'sticker')]),
        ),
    ]
